FROM php:8.2-apache

RUN apt-get update && apt-get install -y git libpq-dev zip libz-dev libzip-dev curl
#RUN apt-get install libfreetype6-dev libjpeg62-turbo-dev libpng-dev 
#RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
#RUN docker-php-ext-install -j$(nproc) gd  
RUN docker-php-ext-install pdo pdo_pgsql pgsql zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN a2enmod rewrite
RUN a2enmod headers

ADD 000-default.conf /etc/apache2/sites-available/000-default.conf

#COPY src/ var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    php-sockets \
    unzip


# Install PHP extensions
RUN apt-get install -y libpq-dev
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo pdo_pgsql 
RUN docker-php-ext-install mbstring exif pcntl gd zip 
RUN docker-php-ext-configure pcntl --enable-pcntl && docker-php-ext-install pcntl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN chmod 755 /var/www/html -R \
    && chown www-data:www-data /var/www/html

# RUN chown -R www-data:www-data /var/www/storage \
#     && chmod -R 775 /var/www/storage

RUN a2enmod rewrite


ADD 000-default.conf /etc/apache2/sites-available/000-default.conf

# Set working directory
WORKDIR /var/www/html

COPY . /var/www/html

RUN ln -s /var/www/html/storage/app /var/www/html/public/storage

RUN composer install
RUN composer update

EXPOSE 80